### Require REST Client VSCode Extenction to run
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Variables
@url=http://localhost:5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzI0M2MxYWI3NTQzMWYyY2ZlODExYSIsImlhdCI6MTU5NzE1NDI2MiwiZXhwIjoxNTk5NzQ2MjYyfQ.glmouwD34ccgNjxImXwWdnZe5WZk1CqCLoSj_O_el8s



### Search Jobs
GET {{url}}/search/kamarier HTTP/1.1


### Register User
POST {{url}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name":"user",
    "email":"bashvtini@gmail.com",
    "password":"12345678",
    "jobTitle":"frontend"
}


### Login User
POST {{url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"bashvtini@gmail.com",
    "password":"Grande1238"
}

### Get User Detail
GET {{url}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Update User Detail
PUT {{url}}/auth/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"user",
    "email":"user@example.com",
    "jobTitle":"kamarier"
}

### Update User Password
PUT {{url}}/auth/update/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currentPassword":"12345678",
    "newPassword":"12345678s"
}

### Get User Jobs
GET {{url}}/auth/jobs HTTP/1.1
Authorization: Bearer {{token}}


### Bookmark Job
POST {{url}}/auth/bookmark HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Vila 7 Kerkon Te Punesoje Kamarier/e",
    "link": "https://www.njoftimefalas.com/23/oferta-njoftime-pune/id-239730"
}


### Get Bookmark
GET {{url}}/auth/bookmark HTTP/1.1
Authorization: Bearer {{token}}


### Check if Job is Bookmarked
POST {{url}}/auth/bookmark/check HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "link":"Job Link"
}


### Forgot Password
POST {{url}}/auth/forgotpassword HTTP/1.1
Content-Type: application/json

{
    "email":"user@example.com"
}

### Reset Password
PUT {{url}}/auth/resetpassword/:resetToken HTTP/1.1
Content-Type: application/json

{
    "password":"123456789"
}

